import test from 'node:test';
import assert from 'node:assert/strict';
import { ponyPose } from '../lib/game/art/pose';
import { createGame } from '../lib/game/simulation';
void test('compression, release and flap have distinct readable poses on the shared clock', () => {
  const s = createGame();
  s.phase = 'compression';
  s.phaseTime = 0.24;
  const compressed = ponyPose(s, 1);
  assert.ok(compressed.yScale < 0.8);
  assert.ok(compressed.xScale > 1.1);
  s.phase = 'flight';
  s.phaseTime = 0;
  const release = ponyPose(s, 1);
  assert.ok(release.yScale > 1.2);
  assert.ok(release.xScale < 0.9);
  s.phaseTime = 1;
  s.flapPose = 0;
  const idle = ponyPose(s, 1);
  s.flapPose = 0.34;
  const flap = ponyPose(s, 1);
  assert.ok(Math.abs(flap.legs[0] - idle.legs[0]) > 0.4);
  assert.notEqual(flap.headAngle, idle.headAngle);
  assert.deepEqual(ponyPose(s, 1), flap);
  s.flipActive = true;
  s.flipProgress = 0.5;
  const tuck = ponyPose(s, 1);
  assert.ok(tuck.yScale < flap.yScale);
});
