/**
 * Shared helpers for the repository's custom lint rules.
 *
 * A helper lands here once a second rule module needs it. Helpers used by one
 * module stay private to that module so this shared surface stays readable.
 */

const SPEC_FILE = /\.(?:test|spec)\.[cm]?[jt]sx?$/;
const CONFIG_FILE = /\.config\.[cm]?[jt]s$/;

/** Normalises the linted file path to forward slashes for stable matching. */
export function filenameOf(context) {
  return context.filename.replace(/\\/g, '/');
}

/** True for a spec file and for the helpers that live beside specs. */
export function isTestFile(context) {
  const name = filenameOf(context);
  return SPEC_FILE.test(name) || name.includes('/tests/');
}

/** True for build and tool configuration, which is not product source. */
export function isConfigFile(context) {
  return CONFIG_FILE.test(filenameOf(context));
}

/** True for ambient type declarations, which carry no executable code. */
export function isDeclarationFile(context) {
  return filenameOf(context).endsWith('.d.ts');
}

/**
 * True for third-party component code generated by the shadcn CLI.
 *
 * These files are re-generated by `pnpm dlx shadcn add`, so a local edit made
 * to satisfy a lint rule is erased on the next update. They are held to the
 * correctness rules only.
 */
export function isVendoredComponent(context) {
  const name = filenameOf(context);
  return name.includes('/components/ui/') || name.includes('/hooks/');
}

/** True for the lint rules themselves, which are tooling rather than product source. */
export function isLintRuleFile(context) {
  return filenameOf(context).includes('/lint-rules/');
}

/** Reads a statically known property name off a member expression. */
export function propertyNameOf(node) {
  if (node?.property?.type === 'Identifier') return node.property.name;
  if (
    node?.property?.type === 'Literal' &&
    typeof node.property.value === 'string'
  ) {
    return node.property.value;
  }
  return null;
}

/** Reads the root identifier of a callee, so `expect(x).not.toBe` resolves to `expect`. */
export function rootCalleeName(node) {
  let current = node;
  while (current) {
    if (current.type === 'Identifier') return current.name;
    if (current.type === 'MemberExpression') current = current.object;
    else if (current.type === 'CallExpression') current = current.callee;
    else if (current.type === 'TSNonNullExpression')
      current = current.expression;
    else return null;
  }
  return null;
}

/**
 * Walks every child node of an AST node, skipping the `parent` back-reference
 * so the traversal cannot cycle.
 */
export function eachChild(node, visit) {
  for (const key of Object.keys(node)) {
    if (key === 'parent') continue;
    visitValue(node[key], visit);
  }
}

/** Dispatches one property value, which may hold a node, a node list, or neither. */
function visitValue(value, visit) {
  if (!Array.isArray(value)) {
    visitIfNode(value, visit);
    return;
  }
  for (const item of value) visitIfNode(item, visit);
}

/** Calls the visitor only for values that are AST nodes. */
function visitIfNode(value, visit) {
  if (value && typeof value.type === 'string') visit(value);
}

/** Names the enclosing declaration of a function expression for error messages. */
export function functionNameOf(node) {
  if (node.id?.name) return node.id.name;
  const parent = node.parent;
  if (
    parent?.type === 'VariableDeclarator' &&
    parent.id?.type === 'Identifier'
  ) {
    return parent.id.name;
  }
  if (parent?.type === 'MethodDefinition' || parent?.type === 'Property') {
    if (parent.key?.type === 'Identifier') return parent.key.name;
  }
  if (
    parent?.type === 'PropertyDefinition' &&
    parent.key?.type === 'Identifier'
  ) {
    return parent.key.name;
  }
  return '<anonymous>';
}

/** True when the node is a function of any spelling. */
export function isFunctionNode(node) {
  return (
    node.type === 'FunctionDeclaration' ||
    node.type === 'FunctionExpression' ||
    node.type === 'ArrowFunctionExpression'
  );
}

/**
 * True for hand-written product source: not a test, not build configuration,
 * not an ambient declaration, not generated component code, and not the lint
 * rules themselves. The documentation rules apply only to this set.
 */
export function isAuthoredSource(context) {
  return !(
    isTestFile(context) ||
    isConfigFile(context) ||
    isDeclarationFile(context) ||
    isVendoredComponent(context) ||
    isLintRuleFile(context)
  );
}
